#!/usr/bin/env python3
#script checks if the files in current repo are modified 
import os

bash_command = ['cd ~/PycharmProjects/devops-netology', "git status"]
result_os = os.popen(' && '.join(bash_command)).read()
is_change = False
for result in result_os.split('\n'):
    if result.find('modified') != -1:
        prepare_result = os.popen('pwd').read() + '/' + result.replace('\tmodified:   ', '')
        prepare_result = prepare_result.split('\n')
        print(''.join(prepare_result))
